#!/usr/bin/env python3
"""
artifact_manager.py — Persistent artifacts for pipeline outputs
Supports: markdown reports, HTML pages, CSV data, JSON snapshots
All artifacts in ~/.hermes/artifacts/ with type/date organization
"""

import json, os, pathlib, shutil, sys
from datetime import datetime

ARTIFACTS_DIR = pathlib.Path("/home/rohit/.hermes/artifacts")
INDEX_FILE = ARTIFACTS_DIR / "index.json"

def init():
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    if not INDEX_FILE.exists():
        INDEX_FILE.write_text(json.dumps({"artifacts": []}, indent=2))

def save_artifact(name, content, fmt="md", tags=None, source=None):
    init()
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    slug = name.lower().replace(" ", "_").replace("/", "_")
    ext = {"md": ".md", "html": ".html", "csv": ".csv", "json": ".json", "txt": ".txt"}.get(fmt, ".md")
    fname = f"{ts}_{slug}{ext}"
    fpath = ARTIFACTS_DIR / fname
    fpath.write_text(content)

    entry = {
        "id": slug,
        "name": name,
        "fmt": fmt,
        "path": str(fpath),
        "size": len(content),
        "tags": tags or [],
        "source": source,
        "created_at": datetime.now().isoformat()
    }
    index = json.loads(INDEX_FILE.read_text())
    index["artifacts"].append(entry)
    INDEX_FILE.write_text(json.dumps(index, indent=2))
    return entry

def list_artifacts(tag=None, limit=20):
    init()
    index = json.loads(INDEX_FILE.read_text())
    artifacts = index["artifacts"]
    if tag:
        artifacts = [a for a in artifacts if tag in a.get("tags", [])]
    return artifacts[-limit:]

def format_artifact_report(pipeline_results=None):
    """Generate a daily markdown report from pipeline state"""
    lines = [
        f"# Homelab Pipeline Report — {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "## Summary",
    ]
    if pipeline_results:
        stages = len(pipeline_results)
        successes = sum(1 for r in pipeline_results if r.get("status") == "success")
        lines.append(f"- Pipeline: {successes}/{stages} stages passed")
        lines.append(f"- Duration: {sum(r.get('elapsed', 0) for r in pipeline_results):.1f}s")
        for r in pipeline_results:
            icon = "✅" if r.get("status") == "success" else "❌"
            lines.append(f"  {icon} {r.get('label', r.get('script', '?'))}: {r.get('status', '?')} ({r.get('elapsed', 0)}s)")

    # Read current system state
    import subprocess
    try:
        r = subprocess.run(["docker", "ps", "--format", "{{.Names}}"], capture_output=True, text=True, timeout=10)
        containers = [c.strip() for c in r.stdout.strip().split("\n") if c.strip()]
        lines.append(f"\n- Containers: {len(containers)} running")
    except:
        pass

    r = subprocess.run(["free", "-h"], capture_output=True, text=True, timeout=5)
    lines.append(f"\n## Resources\n```\n{r.stdout.strip()}\n```")

    lines.append(f"\n---\n_Generated by Hermes Homelab at {datetime.now().isoformat()}_")
    return "\n".join(lines)

if __name__ == "__main__":
    init()
    if len(sys.argv) > 1 and sys.argv[1] == "list":
        for a in list_artifacts():
            print(f"{a['created_at'][:19]} [{a['fmt']:4}] {a['name']} ({a['size']}b)")
    elif len(sys.argv) > 1 and sys.argv[1] == "report":
        text = format_artifact_report()
        save_artifact("daily_report", text, fmt="md", tags=["daily", "homelab"])
        print(f"Saved daily report ({len(text)}b)")
    else:
        print("Usage: artifact_manager.py [list|report]")