#!/usr/bin/env python3
"""regression_test.py - pre-commit regression checks for Hermes/Telegram flows."""
import json
import os
import sys
import glob
from pathlib import Path

_BRIDGE = os.environ.get("TELEGRAM_BRIDGE_URL", "http://127.0.0.1:9199")
_DEFAULT_CHAT = os.environ.get("TELEGRAM_HOME_CHANNEL", "-1003976074764")
def _bridge_key() -> str:
    k = os.environ.get("BRIDGE_AUTH_KEY")
    if k:
        return k
    try:
        for line in Path("/home/rohit/.hermes/.env").read_text().splitlines():
            if line.startswith("BRIDGE_AUTH_KEY="):
                return line.partition("=")[2]
    except Exception:
        pass
    return ""


_AUTH = "Bearer " + _bridge_key()


def _post(ep, d, t=15):
    import urllib.request
    url = _BRIDGE + ep
    body = json.dumps(d).encode()
    req = urllib.request.Request(
        url, data=body,
        headers={"Content-Type": "application/json", "Authorization": _AUTH},
    )
    try:
        with urllib.request.urlopen(req, timeout=t) as r:
            return True, json.loads(r.read())
    except Exception as e:
        return False, {"status": "error", "message": str(e)}


def _send_tg(text, cid=None):
    import time as _t
    ok, p = _post("/telegram-send", {
        "text": f"{text} [{_t.strftime('%m%d%H%M%S')}]",
        "chat_id": cid or _DEFAULT_CHAT,
        "parse_mode": "HTML",
    })
    if not ok:
        return False, p
    # Bridge returns {"status":"ok","throttled":true,"category":...} without a
    # "response" payload when the send was accepted but throttled; otherwise
    # {"status":"ok","response":{...}} where response=Telegram's payload.
    if p.get("throttled"):
        return True, p
    # Deduped = bridge accepted an identical recent message (reachability + auth
    # OK); unique per-run timestamp makes this rare, but never a false FAIL.
    if p.get("deduped"):
        return True, p
    resp = p.get("response", {}) if isinstance(p, dict) else {}
    tg_ok = resp.get("ok") is True
    mid = resp.get("result", {}).get("message_id", "?")
    return tg_ok, mid


def _retrieve(label, fn):
    try:
        code, detail = fn()
        prefix = "PASS:" if code == 0 else "FAIL:"
        return (code, f"{prefix} {detail}")
    except Exception as e:
        return (1, f"ERROR: {str(e)[:150]}")


# --- Tests ---

def test_bridge_ping():
    ok, p = _post("/ping", {"text": "ping"})
    if not ok:
        return 1, p.get("message", "?")[:80]
    pong = (p.get("pong") is True or p.get("status") == "ok")
    return (0 if pong else 1, f"pong={pong}")


def test_telegram_send():
    ok, detail = _send_tg("regression test")
    if isinstance(detail, dict) and detail.get("status") == "ok":
        # Throttled or direct-sent: bridge accepted the message (reachability + auth OK).
        # Throttled sends return {"status":"ok","throttled":true} with no response payload;
        # actual delivery to Telegram was verified separately. Treat as PASS.
        return 0, f"accepted (throttled={detail.get('throttled', False)} cat={detail.get('category', '?')})"
    if ok:
        return 0, f"msg_id={detail}"
    return 1, str(detail)[:80]


def test_docker_ps():
    import subprocess
    try:
        r = subprocess.run(
            ["docker", "ps", "--format", "{{.Names}}"],
            capture_output=True, text=True, timeout=30,
        )
        names = [n for n in r.stdout.splitlines() if n]
        critical = {"hermes", "healthchecks"}
        missing = critical - set(names)
        if missing:
            return 1, f"missing critical: {missing}"
        return 0, f"{len(names)} containers, critical OK"
    except Exception as e:
        return 1, str(e)[:120]


def test_autoheal():
    """Autoheal is the self-healing watcher (replaces ollama's watchdog role).
    Must be running so unhealthy containers get restarted automatically."""
    import subprocess
    try:
        r = subprocess.run(
            ["docker", "ps", "--format", "{{.Names}}"],
            capture_output=True, text=True, timeout=30,
        )
        names = [n.strip() for n in r.stdout.splitlines() if n.strip()]
        if "autoheal" not in names:
            return 1, "autoheal container not running"
        return 0, "autoheal running"
    except Exception as e:
        return 1, str(e)[:120]


def test_inventory():
    # Source of truth: ~/services/inventory/inventory.json (generated by inventory.py)
    inv = "/home/rohit/services/inventory/inventory.json"
    if not os.path.exists(inv):
        return 1, "inventory.json missing"
    try:
        with open(inv) as f:
            data = json.load(f)
        # Accept list or dict-with-services
        n = len(data) if isinstance(data, list) else len(data.get("services", {}))
        return 0, f"inventory.json OK ({n} services)"
    except Exception as e:
        return 1, f"bad json: {str(e)[:80]}"


def test_ask():
    ok, p = _post("/ask", {"text": "/ask --category infra hello", "category": "infra"})
    if not ok:
        return 1, p.get("message", "?")[:80]
    # Bridge returns {"text": "..."} directly; for direct HTTP use it exposes the
    # usage banner or an answer. Reachability is the meaningful pre-commit signal.
    t = p.get("text", "") or ""
    usage = "Usage:" in t[:80]
    if not t:
        return 1, "empty response"
    if usage:
        # Endpoint reachable + parses command routing; banner = expected for raw HTTP.
        return 0, "endpoint OK (usage banner - normal for raw bridge call)"
    if "\u274c" in t[:30]:
        return 1, t[:120]
    return 0, f"ok len={len(t)}"



def test_gdrive_owned():
    """Assert gdrive: is authed to rohitmishra1278@gmail.com and its root
    is an OWNED tree containing the 'Job Hunt' folder (not a shared-with-me
    duplicate). Regression: forces the push target to resolve as owned content."""
    import subprocess
    try:
        r = subprocess.run(
            ["rclone", "lsf", "-d", "gdrive:/"],
            capture_output=True, text=True, timeout=30,
        )
    except FileNotFoundError:
        return 1, "rclone missing"
    except Exception as e:
        return 1, str(e)[:120]
    if r.returncode != 0:
        err = (r.stderr or r.stdout)[:160]
        if "empty token" in err or "401" in err or "failed to make oauth" in err:
            return 1, "gdrive token expired/shared-client. Run: rclone config reconnect gdrive: --drive-auth-url https://accounts.google.com/o/oauth2/auth"
        return 1, err
    top = [l.strip().rstrip("/") for l in r.stdout.splitlines() if l.strip()]
    if not any(x.lower() == "job hunt" for x in top):
        return 1, "Job Hunt NOT at gdrive: owned root -> %s (shared-with-me drift?)" % (top[:8],)
    return 0, "owned root OK: %s" % (top[:5],)



ALL_TESTS = [
    ("bridge-ping", test_bridge_ping),
    ("tg-send", test_telegram_send),
    ("docker-ps", test_docker_ps),
    ("autoheal", test_autoheal),
    ("inventory", test_inventory),
    ("ask-func", test_ask),
    ("gdrive-owned", test_gdrive_owned),
]


def main():
    passed = failed = 0
    for label, fn in ALL_TESTS:
        code, detail = _retrieve(label, fn)
        status = "PASS" if code == 0 else "FAIL"
        if code == 0:
            passed += 1
        else:
            failed += 1
        print(f"[{status}] {label}: {detail}")

    print()
    if failed == 0:
        print(f"ALL PASSED ({passed}/{passed})")
    else:
        print(f"FAILURES: {failed} failed, {passed} passed")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
