#!/bin/bash
# Reflective Phase - Crystallize successful sessions into skills
cd /home/rohit/.hermes/hermes-agent
python3 -c "
import sys, datetime
sys.path.insert(0, '/home/rohit/.hermes/hermes-agent')
from reflective_phase import run_reflective_phase
print(run_reflective_phase(limit=5))
print('[reflective_phase] reflective phase complete at ' + datetime.datetime.now().isoformat())
" 2>&1 | tee -a /home/rohit/.hermes/logs/reflective_phase.log

# --- Memory Delta Phase: extract key learnings into persona prompt ---
python3 << 'MDPYEOF'
import json, os, subprocess
from pathlib import Path
from datetime import datetime, timezone

HERMES_HOME = Path(os.environ.get("HERMES_HOME", Path.home() / ".hermes"))
STATE_DIR = HERMES_HOME / "state"
DELTAS_FILE = STATE_DIR / "memory_deltas.jsonl"
SOUL_FILE = HERMES_HOME / "SOUL.md"

# Collect today's cron logs for interesting observations
logs = []
for logfile in sorted((HERMES_HOME / "logs").glob("*.log")):
    if logfile.stat().st_mtime > (datetime.now().timestamp() - 86400 * 2):
        try:
            last = subprocess.run(
                ["tail", "-20", str(logfile)],
                capture_output=True, text=True, timeout=10
            ).stdout.strip()
            if last:
                logs.append(f"--- {logfile.name} ---\n{last}")
        except Exception:
            pass

# Build a summary prompt
summary_input = "\n".join(logs[-5:])  # last 5 log files

if summary_input.strip():
    try:
        import urllib.request
        payload = json.dumps({
            "model": "llama-3.2-3b-instruct-q4_k_m.gguf",
            "messages": [{
                "role": "user",
                "content": f"From these homelab logs, extract 1-3 key observations about system health, patterns, or maintenance needs. Be concise.\n\n{summary_input[:2000]}"
            }],
            "max_tokens": 500,
            "temperature": 0.1
        }).encode()
        req = urllib.request.Request(
            "http://localhost:18090/v1/chat/completions",
            data=payload,
            headers={"Content-Type": "application/json"}
        )
        with urllib.request.urlopen(req, timeout=120) as resp:
            result = json.loads(resp.read())
            insight = (result.get("choices") or [{}])[0].get("message", {}).get("content", "")
            if insight:
                entry = {
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "source": "reflective_phase",
                    "insight": insight.strip()
                }
                STATE_DIR.mkdir(parents=True, exist_ok=True)
                with open(DELTAS_FILE, "a") as f:
                    f.write(json.dumps(entry) + "\n")
                print(f"[memory_delta] Recorded insight: {insight[:100]}...")
    except Exception as e:
        print(f"[memory_delta] Error: {e}")
else:
    print("[memory_delta] No recent logs to analyze")

# Clean: keep only last 30 deltas
if DELTAS_FILE.exists():
    with open(DELTAS_FILE) as f:
        lines = [l for l in f if l.strip()]
    with open(DELTAS_FILE, "w") as f:
        f.writelines(lines[-30:])

    # Also write latest 3 insights to recent_insights.md for agent reference
    INSIGHTS_FILE = Path("/home/rohit/agentharness/data/recent_insights.md")
    if DELTAS_FILE.exists():
        with open(DELTAS_FILE) as f:
            lines2read = [l for l in f if l.strip()]
        latest = lines2read[-3:]
        with open(INSIGHTS_FILE, "w") as f:
            f.write("# Recent Insights - Chaguli Self-Knowledge\n")
            for entry in latest:
                try:
                    data = json.loads(entry)
                    ts = data.get("timestamp", "")[:10]
                    insight = data.get("insight", "")
                    f.write(f"- ({ts}) {insight}\n")
                except Exception:
                    pass
            f.write("\n---\n*Auto-generated by reflective phase*\n")
        print(f"[memory_delta] Wrote {len(latest)} insights to recent_insights.md")
MDPYEOF
